# Generated by Django 4.2.13 on 2024-06-03 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('city', models.ForeignKey(help_text='Город проведения соревнований', on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город проведения соревнований')),
                ('disciplines', models.ManyToManyField(help_text='Дисциплины', related_name='competitions', to='main.disciplinename', verbose_name='Дисциплины')),
                ('teams', models.ManyToManyField(help_text='Состав команд участников', related_name='competition_teams', to='main.team', verbose_name='Состав команд участников')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ('date_start',),
                'permissions': [('list_view_competition', 'Can view list of Соревнование'), ('list_team_competition', 'Can view list of Команда on Соревнование'), ('delete_team_competition', 'Can delete Команда from Соревнование')],
            },
        ),
    ]
