# Generated by Django 4.2.10 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("location", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
                "ordering": ("date_start",),
                "permissions": [
                    ("list_view_competition", "Can view list of Соревнование"),
                    (
                        "list_team_competition",
                        "Can view list of Команда on Соревнование",
                    ),
                    ("delete_team_competition", "Can delete Команда from Соревнование"),
                ],
            },
        ),
    ]
