# Generated by Django 4.2.11 on 2024-03-10 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "main", "0002_add_relations"
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("location", models.CharField(max_length=250)),
                ("is_active", models.BooleanField(default=True)),
                ('city', models.ForeignKey(
                    help_text='Город проведения соревнований',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='main.city',
                    verbose_name='Город проведения соревнований')),
                ('teams', models.ManyToManyField(
                    help_text='Состав команд участников',
                    related_name='competition_teams',
                    to='main.team',
                    verbose_name='Состав команд участников')),
            ],
            options={
                "verbose_name": "Соревнование",
                "verbose_name_plural": "Соревнования",
                "ordering": (
                    "date_start",
                ),
                "permissions": [
                    (
                        "list_view_competition",
                        "Может видеть список Соревнований"),
                    (
                        "list_team_competition",
                        "Может видеть список команд на Соревновании",
                    ),
                    (
                        "delete_team_competition",
                        "Может удалять команду из Соревнования",
                    ),
                ],
            },
        ),
    ]
