# Generated by Django 4.2.13 on 2024-05-31 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="city",
            field=models.ForeignKey(
                help_text="Город проведения соревнований",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
                verbose_name="Город проведения соревнований",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="disciplines",
            field=models.ManyToManyField(
                help_text="Дисциплины",
                related_name="competitions",
                to="main.disciplinename",
                verbose_name="Дисциплины",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                help_text="Состав команд участников",
                related_name="competition_teams",
                to="main.team",
                verbose_name="Состав команд участников",
            ),
        ),
    ]
