# Generated by Django 4.2.11 on 2024-03-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="city",
            field=models.ForeignKey(
                help_text="Город проведения соревнований",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
                verbose_name="Город проведения соревнований",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="teams",
            field=models.ManyToManyField(
                help_text="Состав команд участников",
                related_name="competition_teams",
                to="main.team",
                verbose_name="Состав команд участников",
            ),
        ),
    ]
