# Generated by Django 4.2.10 on 2024-04-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_alter_event_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="is_active",
        ),
    ]
