# Generated by Django 4.2.8 on 2023-12-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="diagnosis",
            field=models.ForeignKey(
                help_text="Диагноз",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_diagnosis",
                to="main.diagnosis",
                verbose_name="Диагноз",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="discipline",
            field=models.ForeignKey(
                help_text="Дисциплина",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_disciplines",
                to="main.discipline",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AlterField(
            model_name="staffteammember",
            name="staff_member",
            field=models.ForeignKey(
                help_text="Сотрудник",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.staffmember",
                verbose_name="Сотрудник",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="city",
            field=models.ForeignKey(
                help_text="Город откуда команда",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.city",
                verbose_name="Город откуда команда",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="discipline_name",
            field=models.ForeignKey(
                help_text="Дисциплина команды",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.disciplinename",
                verbose_name="Дисциплина команды",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="staff_team_member",
            field=models.ForeignKey(
                help_text="Сотрудник команды",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.staffteammember",
                verbose_name="Сотрудник команды",
            ),
        ),
    ]
