# Generated by Django 4.2.8 on 2023-12-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='document',
            field=models.ForeignKey(blank=True, default='', help_text='Документ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_documemts', to='main.document', verbose_name='Документ'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('discipline_name', 'discipline_level'), name='discipline_name_level_unique'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('position', 'number'), name='player_position_number_unique'),
        ),
    ]
