# Generated by Django 4.2.8 on 2023-12-12 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название')),
                ('number', models.CharField(help_text='Номер соревнований', max_length=256, verbose_name='Номер соревнований')),
                ('date', models.DateField(help_text='Дата соревнований', verbose_name='Дата соревнований')),
                ('duration', models.IntegerField(default=0, help_text='Длительность', verbose_name='Длительность')),
                ('is_active', models.BooleanField(default=True, help_text='Активно', verbose_name='Активно')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Класс', max_length=10, unique=True, verbose_name='Класс')),
                ('is_wheeled', models.BooleanField(default=False, help_text='На коляске', verbose_name='На коляске')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Соревнование команды',
                'verbose_name_plural': 'Совревнования команд',
                'default_related_name': 'team_competitions',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='--ПУСТО--', help_text='Фамилия', max_length=256, verbose_name='Фамилия')),
                ('name', models.CharField(default='--ПУСТО--', help_text='Имя', max_length=256, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='--ПУСТО--', help_text='Отчество', max_length=256, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(help_text='Дата рождения', null=True, verbose_name='Дата рождения')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
            ],
            options={
                'ordering': ('surname', 'name', 'patronymic'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тренер команды',
                'verbose_name_plural': 'Тренер команд',
                'default_related_name': 'trainer_teams',
            },
        ),
        migrations.RemoveField(
            model_name='health',
            name='anamnesis',
        ),
        migrations.RemoveField(
            model_name='health',
            name='player',
        ),
        migrations.RemoveField(
            model_name='health',
            name='respiratory_failure',
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='playerteam',
            options={'verbose_name': 'Игрок команды', 'verbose_name_plural': 'Игроки команды'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Игоровая позиция', 'verbose_name_plural': 'Игровые позиции'},
        ),
        migrations.RemoveConstraint(
            model_name='player',
            name='player_unique',
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='team_location_unique',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='player',
            name='identification_card',
            field=models.TextField(default=0, help_text='Удостоверение личности', verbose_name='Удостоверение личности'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='is_assistent',
            field=models.BooleanField(default=False, help_text='Ассистент', verbose_name='Ассистент'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='is_captain',
            field=models.BooleanField(default=False, help_text='Капитан', verbose_name='Капитан'),
        ),
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.CharField(default='--ПУСТО--', help_text='Возраст', max_length=256, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='team',
            name='composition',
            field=models.CharField(default='--ПУСТО--', help_text='Состав', max_length=256, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='--ПУСТО--', help_text='Имя', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='patronymic',
            field=models.CharField(blank=True, default='--ПУСТО--', help_text='Отчество', max_length=256, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='player',
            name='surname',
            field=models.CharField(default='--ПУСТО--', help_text='Фамилия', max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='number',
            field=models.CharField(help_text='Номер игорока', max_length=256, verbose_name='Номер игорока'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='player',
            field=models.ForeignKey(help_text='Игрок', on_delete=django.db.models.deletion.CASCADE, related_name='player_teams', to='main.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Позиция игрока', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.position', verbose_name='Позиция игрока'),
        ),
        migrations.AlterField(
            model_name='playerteam',
            name='team',
            field=models.ForeignKey(help_text='Команда', on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='main.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Название', max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='team',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='Дисциплина команды', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.discipline', verbose_name='Дисциплина команды'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'patronymic', 'date_of_birth'), name='player_unique'),
        ),
        migrations.DeleteModel(
            name='Anamnesis',
        ),
        migrations.DeleteModel(
            name='Health',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='RespiratoryFailure',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='team',
            field=models.ForeignKey(help_text='Команда', on_delete=django.db.models.deletion.CASCADE, to='main.team', unique=True, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='trainer',
            field=models.ForeignKey(help_text='Тренер команды', on_delete=django.db.models.deletion.CASCADE, to='main.trainer', verbose_name='Тренер команды'),
        ),
        migrations.AddField(
            model_name='teamcompetition',
            name='competition',
            field=models.ForeignKey(help_text='Соревнование', on_delete=django.db.models.deletion.CASCADE, to='main.competition', verbose_name='Соревнование'),
        ),
        migrations.AddField(
            model_name='teamcompetition',
            name='team',
            field=models.ForeignKey(help_text='Команда', on_delete=django.db.models.deletion.CASCADE, to='main.team', unique=True, verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='competition',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='player',
            name='diagnosis',
            field=models.ForeignKey(default=0, help_text='Диагноз', on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='main.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.ForeignKey(default=0, help_text='Пол', on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='main.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='playerteam',
            name='qualificationalification',
            field=models.ForeignKey(blank=True, help_text='Квалификация игрока', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.qualification', verbose_name='Квалификация игрока'),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город откуда команда', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city', verbose_name='Город откуда команда'),
        ),
    ]
