# Generated by Django 4.2.13 on 2024-06-27 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setting_disciplines'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDataPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные игры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_data_players', to='main.player')),
            ],
            options={
                'verbose_name': 'Данные игрока',
                'verbose_name_plural': 'Данные игроков',
            },
        ),
    ]
