# Generated by Django 4.2.8 on 2023-12-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_competition_diagnosis_gender_qualification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterField(
            model_name='teamcompetition',
            name='team',
            field=models.ForeignKey(help_text='Команда', on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='trainerteam',
            name='team',
            field=models.ForeignKey(help_text='Команда', on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='Команда'),
        ),
    ]
