# Generated by Django 4.2.7 on 2023-12-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='revision',
            field=models.CharField(blank=True, max_length=256, verbose_name='Пересмотр класса ХДН'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол'),
        ),
    ]
