# Generated by Django 4.2.8 on 2023-12-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_diagnosis_alter_player_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='player_position_number_unique',
        ),
    ]
