# Generated by Django 4.2.8 on 2023-12-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_competition_options_alter_trainer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Название', max_length=256, verbose_name='Название'),
        ),
    ]
