# Generated by Django 4.2.13 on 2024-07-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamedataplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameDataPlayer',
        ),
    ]
