# Generated by Django 4.2.13 on 2024-07-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_gamedataplayer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameDataPlayer",
        ),
    ]
