# Generated by Django 4.2.13 on 2024-07-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gamedataplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedataplayer',
            options={'default_related_name': 'game_data_player', 'verbose_name': 'JSON данные игрока для нарезки видео', 'verbose_name_plural': 'JSON данные игроков для нарезки видео'},
        ),
        migrations.AlterField(
            model_name='gamedataplayer',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Данные игры'),
        ),
        migrations.AlterField(
            model_name='gamedataplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
    ]
