# Generated by Django 4.2.8 on 2023-12-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_curator'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='player_unique',
        ),
    ]
