# Generated by Django 4.2.8 on 2023-12-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='Дата рождения'),
        ),
    ]
