# Generated by Django 4.2.13 on 2024-08-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_gamedataplayer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='player_unique',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'surname', 'patronymic', 'birthday', 'position', 'number'), name='player_unique'),
        ),
    ]
