# Generated by Django 4.2.8 on 2023-12-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'city', 'discipline'), name='team_city_unique'),
        ),
        migrations.AddConstraint(
            model_name='trainerteam',
            constraint=models.UniqueConstraint(fields=('trainer', 'team'), name='trainer_teams_unique'),
        ),
    ]
