# Generated by Django 4.2.8 on 2023-12-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_team_team_city_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerteam',
            old_name='qualificationalification',
            new_name='qualification',
        ),
    ]
