# Generated by Django 4.2.9 on 2024-01-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_team_curator_alter_team_staff_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-date_start',),
            },
        ),
        migrations.CreateModel(
            name='TeamInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='main.event', verbose_name='Ивент')),
                ('team_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_on_event', to='main.team', verbose_name='Команда')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='team_event',
            field=models.ManyToManyField(null=True, related_name='events', through='main.TeamInEvent', to='main.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_event',
            field=models.ManyToManyField(null=True, related_name='teams', through='main.TeamInEvent', to='main.event'),
        ),
    ]
