# Generated by Django 4.2.9 on 2024-01-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_team_curator_alter_team_staff_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(help_text='Город проведения соревнований', on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город проведения соревнований')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
                'ordering': ('-date_start',),
            },
        ),
        migrations.CreateModel(
            name='TeamInEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='main.event', verbose_name='Соревнование')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_on_event', to='main.team', verbose_name='Команда')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(help_text='Состав команд участников', related_name='teams', through='main.TeamInEvent', to='main.team', verbose_name='Состав команд участников'),
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(help_text='Соревнования в которых участвует команда', related_name='events', through='main.TeamInEvent', to='main.event', verbose_name='Соревнования в которых участвует команда'),
        ),
    ]
