# Generated by Django 4.2.9 on 2024-02-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_document_file_alter_document_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="staff_team_member",
        ),
        migrations.AddField(
            model_name="staffteammember",
            name="team",
            field=models.ManyToManyField(
                help_text="Команда",
                related_name="team_members",
                to="main.team",
                verbose_name="Команда",
            ),
        ),
    ]
