# Generated by Django 4.2.8 on 2024-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_staffteammember_staff_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffteammember',
            name='staff_position',
            field=models.CharField(choices=[('trainer', 'тренер'), ('other', 'другой')], default='', help_text='Статус сотрудника', max_length=256, verbose_name='Статус сотрудника'),
        ),
    ]
