# Generated by Django 4.2.10 on 2024-02-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_staffteammember_staff_position"),
        ("main", "0013_player_addition_date_and_more"),
    ]

    operations = []
