# Generated by Django 4.2.10 on 2024-02-25 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0014_merge_20240225_1810"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="curator",
            field=models.ForeignKey(
                help_text="Куратор команды",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Куратор команды",
            ),
        ),
    ]
