# Generated by Django 4.2.10 on 2024-03-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_team_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffteammember',
            name='staff_position',
            field=models.CharField(choices=[('trainer', 'тренер'), ('other', 'пушер-тьютор')], default='', help_text='Статус сотрудника', max_length=256, verbose_name='Статус сотрудника'),
        ),
    ]
