# Generated by Django 4.2.10 on 2024-03-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_player_birthday_alter_player_gender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffteammember",
            options={
                "permissions": [
                    ("list_view_staff", "Can view list of Персонала команды")
                ],
                "verbose_name": "Сотрудник команды",
                "verbose_name_plural": "Сотрудники команды",
            },
        ),
    ]
