# Generated by Django 4.2.10 on 2024-03-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_staffmember_phone"),
        ("main", "0019_alter_staffteammember_options"),
    ]

    operations = []
