# Generated by Django 4.2.10 on 2024-03-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_player_name_alter_player_patronymic_and_more"),
        ("main", "0020_merge_20240324_2257"),
    ]

    operations = []
