# Generated by Django 4.2.10 on 2024-04-02 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_merge_20240325_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=256, unique=True, upload_to="players_documents"
            ),
        ),
    ]
