# Generated by Django 4.2.10 on 2024-04-06 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_merge_20240325_1816"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="discipline",
        ),
        migrations.AddField(
            model_name="player",
            name="discipline_level",
            field=models.ForeignKey(
                help_text="Числовой статус",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_disciplines_levels",
                to="main.disciplinelevel",
                verbose_name="Числовой статус",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="discipline_name",
            field=models.ForeignKey(
                help_text="Дисциплина",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_disciplines_names",
                to="main.disciplinename",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=256, unique=True, upload_to="players_documents"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(
                default="",
                help_text="Имя",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отчество",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="surname",
            field=models.CharField(
                default="",
                help_text="Фамилия",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="name",
            field=models.CharField(
                default="",
                help_text="Имя",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отчество",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="surname",
            field=models.CharField(
                default="",
                help_text="Фамилия",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
