# Generated by Django 4.2.10 on 2024-04-02 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_merge_20240325_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                max_length=256, unique=True, upload_to="players_documents"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(
                default="",
                help_text="Имя",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отчество",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="surname",
            field=models.CharField(
                default="",
                help_text="Фамилия",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="name",
            field=models.CharField(
                default="",
                help_text="Имя",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="patronymic",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Отчество",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="surname",
            field=models.CharField(
                default="",
                help_text="Фамилия",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[А-Яа-яё -]+$",
                        "Строка должны состоять из кирилических или латинских символов.Возможно использование дефиса.",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
