# Generated by Django 4.2.10 on 2024-04-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="discipline",
        ),
        migrations.AddField(
            model_name="player",
            name="discipline_level",
            field=models.ForeignKey(
                help_text="Числовой статус",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_disciplines_levels",
                to="main.disciplinelevel",
                verbose_name="Числовой статус",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="discipline_name",
            field=models.ForeignKey(
                help_text="Дисциплина",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_disciplines_names",
                to="main.disciplinename",
                verbose_name="Дисциплина",
            ),
        ),
    ]
