# Generated by Django 4.2.10 on 2024-04-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_remove_player_discipline_player_discipline_level_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Discipline",
        ),
    ]
