# Generated by Django 4.2.10 on 2024-04-11 06:47

from core.constants import DISCIPLINES
from django.db import migrations


def set_default_disciplines(apps, schema_editor):
    DisciplineName = apps.get_model("main", "DisciplineName")
    DisciplineName.objects.bulk_create(
        [DisciplineName(name=name) for name in set(DISCIPLINES)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_delete_discipline"),
    ]

    operations = [
        migrations.RunPython(
            set_default_disciplines,
        ),
    ]
