# Generated by Django 4.2.10 on 2024-04-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_delete_discipline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="level_revision",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Игровая классификация",
                verbose_name="Игровая классификация",
            ),
        ),
    ]
