# Generated by Django 4.2.10 on 2024-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_alter_player_level_revision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffteammember",
            name="team",
            field=models.ManyToManyField(
                blank=True,
                default="Свободный агент",
                help_text="Команда",
                related_name="team_members",
                to="main.team",
                verbose_name="Команда",
            ),
        ),
    ]
