# Generated by Django 4.2.11 on 2024-05-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_staffteammember_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="video_frame_info",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Метаинформация с видео о игроке",
                null=True,
                verbose_name="Метаинформация с видео о игроке",
            ),
        ),
    ]
