# Generated by Django 4.2.10 on 2024-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Представитель команды", "Представитель команды"),
                    ("Модератор", "Модератор"),
                    ("Администратор", "Администратор"),
                ],
                default="Представитель команды",
                help_text="Уровень прав доступа",
                max_length=21,
                verbose_name="Роль",
            ),
        ),
    ]
