# Generated by Django 4.2.13 on 2024-06-03 19:22

import core.constants
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unload_name', models.CharField(default='Выгрузка', max_length=core.constants.MainConstantsInt['CHAR_FIELD_LENGTH'], verbose_name='Имя выгрузки')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выгрузки')),
                ('unload_file_slug', models.FileField(upload_to='unloads_data/', verbose_name='Ссылка на файл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Выгрузку',
                'verbose_name_plural': 'Выгрузки',
                'ordering': ('date',),
                'permissions': [('list_view_unload', 'Can view list of Выгрузку')],
            },
        ),
    ]
