# Generated by Django 4.2.13 on 2024-05-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unload_name",
                    models.CharField(
                        default="Выгрузка", max_length=256, verbose_name="Имя выгрузки"
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата выгрузки"),
                ),
                (
                    "unload_file_slug",
                    models.FileField(
                        upload_to="unloads_data/", verbose_name="Ссылка на файл"
                    ),
                ),
            ],
            options={
                "verbose_name": "Выгрузку",
                "verbose_name_plural": "Выгрузки",
                "ordering": ("date",),
                "permissions": [("list_view_unload", "Can view list of Выгрузку")],
            },
        ),
    ]
