# Generated by Django 4.2.10 on 2024-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unloads", "0002_alter_unload_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unload",
            name="name",
            field=models.CharField(help_text="", max_length=256, verbose_name=""),
        ),
    ]
