# Generated by Django 4.2.10 on 2024-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unloads", "0003_alter_unload_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unload",
            options={
                "ordering": ("date",),
                "verbose_name": "Выгрузку",
                "verbose_name_plural": "Выгрузки",
            },
        ),
        migrations.RenameField(
            model_name="unload",
            old_name="file_slug",
            new_name="unload_file_slug",
        ),
        migrations.RemoveField(
            model_name="unload",
            name="name",
        ),
        migrations.AddField(
            model_name="unload",
            name="unload_name",
            field=models.CharField(
                default="Выгрузка", max_length=256, verbose_name="Имя выгрузки"
            ),
        ),
    ]
