# Generated by Django 4.2.10 on 2024-05-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unloads", "0005_alter_unload_unload_file_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unload",
            options={
                "ordering": ("date",),
                "permissions": [("list_view_unload", "Can view list of Выгрузку")],
                "verbose_name": "Выгрузку",
                "verbose_name_plural": "Выгрузки",
            },
        ),
    ]
