# Generated by Django 4.2.10 on 2024-03-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date_start',), 'permissions': [('list_view_event', 'Can view list of Соревнование'), ('list_team_event', 'Can view list of Команда on Соревнование'), ('delete_team_event', 'Can delete Команда from Соревнование')], 'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
    ]
