version: '3.8'
name: 'ahf_dev_redis'


services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - PORT=6379
      - DATABASES=0
      - HOST=localhost

volumes:
  redis_data:
