# filename: docker-compose.dev.yml
# full path: /home/ahf/ahf_dev/docker-compose.dev.yml
# Description: docker-compose file for local development environment

version: '3.8'
name: ahf_dev

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
  web:
    build: 
      context: ../../
      dockerfile: ./infra/dev/Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value:
