#filename: docker-compose.dev.yaml
#full path: ./infra/dev/docker-compose.dev.yaml
#description: docker-compose file for development environment

version: '3.8'
name: ahf_dev

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env
    ports:
      - 5432:5432

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - HOST=localhost
      - DATABASES=0
      - PORT=6379
    ports:
      - 6379:6379


volumes:
  postgres_db_data:
