# filename: docker-compose.dev.yml
# full path: /home/ahf/ahf_dev/docker-compose.dev.yml
# Description: docker-compose file for local development environment

version: '3.8'
name: ahf_dev

services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  db_data:
