#filename: docker-compose.dev.yaml
#full path: ./infra/dev/docker-compose.dev.yaml
#description: docker-compose file for development environment

version: '3.8'
name: ahf_dev

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env
    ports:
      - 5433:5432

volumes:
  postgres_db_data:
