# Generated by Django 4.2.13 on 2024-05-31 06:49

import core.validators
import django.core.validators
from django.db import migrations, models
import games.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название игры"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        validators=[core.validators.validate_game_date],
                        verbose_name="Дата игры",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(blank=True, verbose_name="Ссылка на видео"),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Игрок")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                games.constants.NumericalValues[
                                    "GAME_MIN_PLAYER_NUMBER"
                                ],
                                "Номер игрока должен быть больше или равен нулю",
                            ),
                            django.core.validators.MaxValueValidator(
                                games.constants.NumericalValues[
                                    "GAME_MAX_PLAYER_NUMBER"
                                ],
                                "Номер игрока должен быть меньше или равен 99",
                            ),
                        ],
                        verbose_name="Номер игрока",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок, участвующий в игре",
                "verbose_name_plural": "Игроки, участвующие в игре",
            },
        ),
        migrations.CreateModel(
            name="GameTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название команды"),
                ),
                (
                    "discipline_name",
                    models.CharField(max_length=256, verbose_name="Дисциплина"),
                ),
            ],
            options={
                "verbose_name": "Команда, участвующая в игре",
                "verbose_name_plural": "Команды, участвующие в игре",
                "ordering": ["name"],
            },
        ),
    ]
