# Generated by Django 4.2.13 on 2024-05-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0028_alter_staffteammember_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название игры"),
                ),
                (
                    "video_link",
                    models.URLField(blank=True, verbose_name="Ссылка на видео"),
                ),
            ],
            options={
                "verbose_name": "Игра",
                "verbose_name_plural": "Игры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GameTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_away",
                    models.BooleanField(default=False, verbose_name="Выездная команда"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Игра, в которой участвует команда",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_teams",
                        to="games.game",
                        verbose_name="Игра",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Команда, участвующая в игре",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_teams",
                        to="main.team",
                        verbose_name="Команда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда в игре",
                "verbose_name_plural": "Команды в играх",
                "unique_together": {("game", "team")},
            },
        ),
        migrations.AddField(
            model_name="game",
            name="teams",
            field=models.ManyToManyField(
                help_text="Команды участвующие в игре",
                through="games.GameTeam",
                to="main.team",
                verbose_name="Команды",
            ),
        ),
    ]
