# Generated by Django 4.2.13 on 2024-07-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_delete_gamedataplayer"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameDataPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные игры")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.player"
                    ),
                ),
            ],
            options={
                "verbose_name": "JSON данные игрока для нарезки видео",
                "verbose_name_plural": "JSON данные игроков для нарезки видео",
                "default_related_name": "game_data_player",
            },
        ),
    ]
