# Generated by Django 4.2.13 on 2024-06-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together=set(),
        ),
    ]
