# Generated by Django 4.2.13 on 2024-05-27 11:28

import core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_competition_disciplines"),
        ("main", "0028_alter_staffteammember_team"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Игрок")),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Номер игрока",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Номер игрока должен быть больше или равен нулю"
                            ),
                            django.core.validators.MaxValueValidator(
                                99, "Номер игрока должен быть меньше или равен 99"
                            ),
                        ],
                        verbose_name="Номер игрока",
                    ),
                ),
                (
                    "game_team",
                    models.CharField(
                        help_text="Команда", max_length=256, verbose_name="Команда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок в игре",
                "verbose_name_plural": "Игроки в игре",
            },
        ),
        migrations.AlterModelOptions(
            name="gameteam",
            options={
                "ordering": ["name"],
                "verbose_name": "Команда в игре",
                "verbose_name_plural": "Команды в игре",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gameteam",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="game",
            name="teams",
        ),
        migrations.AddField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="competitions.competition",
                verbose_name="Соревнование",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[core.validators.validate_game_date],
                verbose_name="Дата игры",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="game_teams",
            field=models.ManyToManyField(
                related_name="teams", to="main.team", verbose_name="Команды"
            ),
        ),
        migrations.AddField(
            model_name="gameteam",
            name="discipline_name",
            field=models.CharField(
                default="test",
                help_text="Дисциплина",
                max_length=256,
                verbose_name="Дисциплина",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gameteam",
            name="game_players",
            field=models.ManyToManyField(
                help_text="Игроки, участвующие в игре",
                related_name="players",
                to="main.team",
                verbose_name="Игроки",
            ),
        ),
        migrations.AddField(
            model_name="gameteam",
            name="name",
            field=models.CharField(
                default="test",
                help_text="Название команды",
                max_length=256,
                verbose_name="Название команды",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date__lte", django.db.models.functions.datetime.Now())
                ),
                name="game_date_must_not_be_in_the_future",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.CheckConstraint(
                check=models.Q(("number__gte", 0)),
                name="player_number_must_be_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.CheckConstraint(
                check=models.Q(("number__lte", 99)), name="player_number_be_99_or_less"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("name", "number")},
        ),
        migrations.RemoveField(
            model_name="gameteam",
            name="game",
        ),
        migrations.RemoveField(
            model_name="gameteam",
            name="is_away",
        ),
        migrations.RemoveField(
            model_name="gameteam",
            name="team",
        ),
    ]
