# Generated by Django 4.2.13 on 2024-06-05 10:12

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="name",
            field=models.CharField(
                max_length=core.constants.UserConstans["NAME_MAX_LENGTH"],
                verbose_name="Фамилия игрока",
            ),
        ),
    ]
