# Generated by Django 4.2.13 on 2024-06-05 10:33

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_gameplayer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="last_name",
            field=models.CharField(
                default="last_name",
                max_length=core.constants.UserConstans["NAME_MAX_LENGTH"],
                verbose_name="Фамилия игрока",
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="name",
            field=models.CharField(
                max_length=core.constants.UserConstans["NAME_MAX_LENGTH"],
                verbose_name="Имя игрока",
            ),
        ),
    ]
