# Generated by Django 4.2.13 on 2024-06-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_gameplayer_last_name_alter_gameplayer_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together=set(),
        ),
    ]
