# Generated by Django 4.2.13 on 2024-06-05 11:10

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_gameplayer_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameplayer",
            name="last_name",
            field=models.CharField(
                max_length=core.constants.UserConstans["NAME_MAX_LENGTH"],
                verbose_name="Фамилия игрока",
            ),
        ),
    ]
