# Generated by Django 4.2.13 on 2024-06-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gameplayer_unique_together'),
        ('games', '0005_alter_gameplayer_last_name'),
    ]

    operations = [
    ]
