# Generated by Django 4.2.13 on 2024-06-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_merge_20240606_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('name', 'number', 'game_team')},
        ),
    ]
