version: '3.8'
name: ahf_stage

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    ports:
      - 5432:${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env

  site:
    image: "${IMAGE_COMPOSE}"
    container_name: adaptive_hockey_federation
    restart: always
    volumes:
      - static_value:/app/adaptive_hockey_federation/static/
      - media_value:/app/adaptive_hockey_federation/media/
    env_file:
      - ../../.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:${PORT}"
    volumes:
      - ../nginx/nginx_stage.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ../../.env
    depends_on:
      - site

volumes:
  static_value:
  media_value:
  postgres_data:
